env = "dev"
[database]
    [database.read]
        addr = "root:123456@tcp(127.0.0.1:3306)/finder?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    [database.write]
        addr = "root:123456@tcp(127.0.0.1:3306)/finder?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
[redis]
    addr = "127.0.0.1:6379"
    psw  = ""
[cache]
    expire = 86400
    limit = 1000